gild/apps/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
# from django.views.generic.base import TemplateView

from . import views

app_name="accounts"

urlpatterns = [
    path('profile', views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path('accounts/login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('accounts/logout', auth_views.LogoutView.as_view(), name="logout")
]

gild/apps/chat/urls.py
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    path("", views.ShowChatHome, name='showchat'),
    path('<str:room_name>/<str:person_name>', views.ShowChatPage, name='showpage'),
]

gild/apps/contact/urls.py
from django.urls import path
from .views import contact

app_name="contact"
urlpatterns = [
    path("", contact, name='contact')
]

gild/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gild.apps.public.urls')),
    path('accounts/', include('gild.apps.accounts.urls')),
    path('contact/', include('gild.apps.contact.urls')),
    path('chat/', include('gild.apps.chat.urls')),
]

gild/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

# Create your models here.
class UserProfile(models.Model):
    #owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    #settings
    is_full_name_displayed = models.BooleanField(default=True)

    #details
    bio = models.CharField(max_length=500, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

    #Links (TODO: Validate Input)
    website = models.URLField(max_length=200, blank=True, null=True)
    linkedin_url = models.URLField(max_length=640, blank=True, null=True)
    twitter_url = models.URLField(max_length=640, blank=True, null=True)
    facebook_url = models.URLField(max_length=640, blank=True, null=True)

gild/apps/chat/models.py
from django.db import models

# Create your models here.

gild/apps/contact/models.py
from django.db import models

# Create your models here.

gild/apps/chat/forms.py
from django import forms

class ChatForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Name"}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "Email"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Message", "rows": 5}))

gild/apps/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Name"}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "Email"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Message", "rows": 5}))

gild/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

gild/apps/chat/views.py
import bleach
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.core.mail import send_mail

from gild import settings
from .forms import ChatForm

def ShowChatHome(request):
    return render(request,"chat_home.html")

def ShowChatPage(request, room_name, person_name):
    return render(request, "chat_screen.html",{'room_name':room_name,'person_name':person_name})
    # return HttpResponse("Chat page"+" "+room_name+" "+person_name)

gild/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.core.mail import send_mail

from gild import settings
from .forms import ContactForm

def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = bleach.clean(form.cleaned_data["name"])
            email = bleach.clean(form.cleaned_data["email"])
            message = bleach.clean(form.cleaned_data["message"])
            send_mail(f"{name} sent you a message!", message, email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, 'contact.html', {"form": form, "success": True})
    else:
        raise NotImplementedError

    return render(request, 'contact.html', {"form": form})

gild/views.py
# # from django.http import HttpResponse
# # from django.template import loader
# from django.shortcuts import render
# from django.views.generic.base import TemplateView
# from django.contrib.auth.mixins import LoginRequiredMixin
#
# def index(request):
#     print(request.user)
#     return render(request, 'index.html')
#     # template = loader.get_template('index.html')
#     # return HttpResponse(template.render({}, request))
#
# def about(request):
#     return render(request, 'about.html')
#
# def contact(request):
#     return render(request, 'contact.html')
#
# class ProfileView(LoginRequiredMixin, TemplateView):
#     template_name = 'accounts/profile.html'

gild/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}

<header class="image text-center">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="image-heading text-uppercase mb-0">About us</h1>
    </div>
</header>

<div class="text-center text-secondary mb-0">
                <p class="title">
                    Hello! Welcome to our Group-making webpage!
                </p>
                <img class="logo" src="static/img/guild.png" alt="Temp logo pic">
                <div class="main-body">
                    <div class="raised-box text-center">
                        <p class="intro-content">
                            Hope your semester has been wrapping up nicely! I am Robert, an RCA at Forbes College and I’m working on a solution to solve all of your loneliness problems now that I’m PTL!

                            There are so many students, freshmen especially, who are looking for ways to make those lifelong Princeton connections. I know many of you are looking forward to meeting people next term, but there is still time now and during the summer! That’s why we’ve decided to build Gild, a project where we will match you with friends you’ll enjoy hanging out with--or we’ll give you your money back! (This is 100% free btw).

                            The goal is to make up for the social time we’ve lost this year, during the summer! We want to give you a group of fellow Princetonians that have similar interests and/or will be in a similar location this summer.
                       </p>
                   </div>
                    <p class="mb-0">
                        If you:
                    </p>
                    <li class="sq-bullet-list">
                        Want to make friends for your upcoming internship
                    </li>
                    <li class="sq-bullet-list">
                        Find people who will be in the same city as you this summer
                    </li>
                    <li class="sq-bullet-list mb-3">
                        Or simply not feel alone
                    </li>
                    Gild will help initialize those connections in our last weeks of spring term and bridge the awkward, digital gap before the summer starts. We would love for you to try out our Discord channel beta test by first filling out this Google Form (it shouldn’t take more than 5 minutes!)

                    By selecting between cities, internship opportunities, social activities, and other interests, we’ll link you with peers who you have the best fit with for lifelong friendships! Our deadline to fill out this form is Wednesday April 28th, after which we will use Discord to begin group selection and get everyone conversating!

                    We’re hoping Gild will alleviate some of the barriers associated with social connections, and though it is late in the semester, we hope you can make a couple lasting connections for this summer and the post-covid fallout that will be your sophomore and junior year! Give us a shot, we promise it’ll be worth it!
                </div>
                <p class="sign-up">
                    <!-- You can also reach us by emailing at <a href="mailto:bryanzin7@gmail.com">bryanzin7@gmail.com</a> -->
                    Sign up with this google <a href="https://docs.google.com/forms/d/e/1FAIpQLSdShyuF92hBqPrXNpSXl3QxN0JnU9dFKkwBAIfqPW2yKhS_GA/viewform?usp=sf_link">form</a>
                </p>
</div>
{% endblock %}

gild/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>
    Login
</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

gild/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}

{% with profile=user.profile %}

<div class="page-profile">
    <div class="page-header header-filter">
    <div class="main main-raised">
        <div class="profile-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 ml-auto mr-auto">
                        <div class="profile">
                            <div class="avatar">
                                <div class="box-1-1">
                                    <div class="profile-image-container">
                                        <img src="http://tinygraphs.com/labs/isogrids/hexa16/Bryan?theme=bythepool&numcolors=4&size=220&fmt=svg" alt="Profile picture">
                                    </div>
                                </div>
                            </div>
                            <div class="name">
                                <h3 class="title">{{ user.get_full_name }} (@{{ user.username }})</h3>
                                {% if profile %}
                                    <h6>{{ profile.persona|default:"" }}</h6>
                                    {% if profile.linkedin_url %}
                                        <a href="{{ profile.linkedin_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-linkedin-in"></i></a>
                                    {% endif %}
                                    {% if profile.twitter_url %}
                                        <a href="{{ profile.twitter_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-twitter"></i></a>
                                    {% endif %}
                                    {% if profile.facebook_url %}
                                        <a href="{{ profile.facebook_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-facebook"></i></a>
                                    {% endif %}
                                    <div class="description text-center">
                                        {% with website=profile.website|default:"" %}
                                            <a href="{{ website }}">{{ website }}</a>
                                        {% endwith %}
                                    </div>
                                    <div class="description text-center">
                                        Interests:
                                        {% for interest in profile.interests.all %}
                                            <span>
                                                {{ interest.name }}{% if not forloop.last %}, {% endif %}
                                            </span>
                                        {% endfor %}
                                    </dir>
                                    <div class="description text-center">
                                        <p>{{ profile.bio|default:"" }}</p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% if profile %}
                {% endif %}
                <br/>
            </div>
        </div>
    </div>
        </div>
</div>
{% endwith %}


{% endblock %}

gild/templates/base.html
<!-- templates/base.html-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Gild{% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <link href="{% static 'css/profile.css' %}" rel="stylesheet" />
    <link href="{% static 'css/about.css' %}" rel="stylesheet" />

</head>
<body>
    {% include 'navbar.html' %}
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'theme/js/scripts.js' %}"></script>
</body>
</html>

gild/templates/chat_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat Home</title>
</head>
<body>
<input type="text" name="room_name" id="room_name" placeholder="Room Name"><br>
<input type="text" name="person_name" id="person_name" placeholder="Your Name"><br>
<input type="button" name="button" value="Click to Start Chat" id="submit">
<script>
    document.querySelector("#submit").onclick=function(e){
        var roomname=document.querySelector("#room_name").value;
        var personname=document.querySelector("#person_name").value;
        window.location.pathname='/chat/'+roomname+'/'+personname;
    }
</script>
</body>
</html>

gild/templates/chat_screen.html
<DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Chat</title>
</head>
<body>
<div style="height:500px;width:100%;overflow-y:scroll" id="div_data">
	

</div>
<div>
	<input type="text" name="message" id="message" placeholder="Message" style="padding:10px;width:100%">

    <input type="button" value="Send Message" id="send_message" style="background:dodgerblue;color:#fff;padding:10px;border:0px;width:100%">
    <script type="text/javascript">
    	var roomname='{{ room_name }}';
    	var personname='{{ person_name }}';
        console.log(roomname);
        console.log(personname);
    	const chatSocket=new WebSocket('ws://'+window.location.host+'/chat/'+roomname+'/'+personname+'/');//+'/ws/chat/'+roomname+'/'+personname+'/');
        console.log(chatSocket.url);
        console.log(chatSocket.readyState);
        chatSocket.onmessage=function(e){
            console.log(e)
        }
        
        chatSocket.onclose=function(e){
            console.log(e)
        }

        document.querySelector("#send_message").onclick=function(e){
            var message=document.querySelector("#message").value;
            chatSocket.send(JSON.stringify({'message':message}))
            document.querySelector("#message").value=''
        }
    </script>
</div>
</body>
</html>

gild/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}

<section class="page-selection" id="contact">
    <div class="container">
        <!-- Contact Section heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Have a question? Contact us here!</h2>
        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-envelope"></i></i></div>
            <div class="divider-custom-line"></div>
        </div>
            <div class="text-center text-secondary mb-0">
                <p>
                    Hello! Welcome to our appreciation webpage!
                </p>
                <p>
                    Send us an email through our form below to ask us questions about the project!
                </p>
                <p>
                    <!-- You can also reach us by emailing at <a href="mailto:bryanzin7@gmail.com">bryanzin7@gmail.com</a> -->
                    You can also reach us by emailing at <a href="mailto:rs36@princeton.edu">rs36@princeton.edu</a>
                </p>
            </div>
        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">
            {% if success %}
                <div class="alert alert-success" role="alert">
                    Your message was sent! We will reply as soon as possible, keep an eye on your inbox!
                </div>
            {% endif %}
            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file in line 19-->
                <form id="contactForm" name="sentMessage" novalidate="novalidate" method="post">
                    {% csrf_token %}
                    {% for field in form %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            {{ field.label_tag }}
                            {{ field }}
                            {% for error in field.errors %}
                                <p class="help-block text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <br />
                    <div class="form-group"><button class="btn hs-bg-primary btn-xl text-white" id="sendMessageButton" type="submit">Send</button></div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

gild/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

<!-- Masthead-->
<header class="masthead text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <!-- <img class="masthead-avatar mb-5" src="{% static 'img/guild.png' %}" alt="" /> -->
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Join the Gild!</h1>
    </div>
</header>

<div class="description text-center">
    <h1 style="padding-top: 100px">In a new space and looking for friends?</h1>
    <h2>Look no further, join our network and find people with similar interests and make genuine connections!</h2>
    <p style="font-size: 30px; padding-top: 100px">
        Gild is a web application that allows users to identify the location, company, and role that they will be working at after graduation and select specific preferences for the attributes of friend groups that they would enjoy spending time with after work.
    </p>
</div>



{% endblock %}

gild/templates/navbar.html
<!-- Navigation-->

{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}
{% url 'accounts:profile' as profile_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}

<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{ index_url }}">GILD</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">Profile</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{ logout_url }}">Logout</a></li>
                {% else %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == login_url %}active{% endif %}" href="{{ login_url }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>